path: /home/pine/Pixus/Model_training
train: images/
val: images/

names:
 0: ortie
 1: sauge
 2: trefle_a_5_feuilles
 3: menthe_sauvage
 4: orchidee_freyesque
 5: edelweiss
 6: graine_de_pandouille
 7: ginseng
 8: belladone
 9: mandragore
 10: perce-neige
 11: salikrone
 12: frene
 13: chataignier
 14: bambou
 15: merisier
 16: noisetier
 17: ebene
 18: kaliptus
 19: charme
 20: bambou_sombre
 21: orme
 22: bambou_sacre
 23: tremble
 24: aquajou
 25: fer
 26: cuivre
 27: bronze
 28: kobalte
 29: manganese
 30: etain
 31: silicate
 32: argent
 33: bauxite
 34: or
 35: dolomite
 36: obsidienne
 37: ecume_de_mer
 38: ble
 39: orge
 40: avoine
 41: houblon
 42: lin
 43: seigle
 44: riz
 45: malt
 46: chanvre
 47: mais
 48: millet
 49: frostiz
 50: quisnoa
 51: goujon
 52: greuvette
 53: truite
 54: crabe
 55: poisson_chaton
 56: poisson_pane
 57: carpe_diem
 58: sardine_brillante
 59: brochet
 60: kralamoure
 61: anguille
 62: noyer
 63: chene
 64: bombu
 65: erable
 66: oliviolet
 67: if
 68: doracle_grise
 69: perche
 70: raie
 71: lotte
 72: requin_marteau_faucille
 73: bar_rikain
 74: morue
 75: tanche
 76: espadon
 77: poisskaille
 78: patelle
 79: eau_potable
